#[cfg(feature = "bytecode")]
mod test_bytecode;
mod test_permissions;
mod test_runtime;
mod test_grammar;
mod test_tc_files;
mod test_validators;
mod test_embed;
mod test_control_flow;
mod test_functions;
mod test_stdlib_core;
mod test_stdlib_io;
mod test_stdlib_net;
mod test_stdlib_db;
mod test_patterns;
mod test_types;
mod test_async;
mod test_security;
mod test_golden;
